
const tags = [
    'implementation',    
    'greedy',
    'dp',
    'math',
    'binary search',
    'data structure',
    'constructive algorithms',
    'brute force',
    'sortings',
    'dfs and similar',
    'trees',
    'graphs',
    'strings',
    'number theory',
    'combinatorics',
    'two pointers',
    'geometry',
    'bitmasks',
    'flows',
    'games',
    'interactive',
    'shortest paths',
    'divide and conquer',
    'probabilities',
    'hashing',
    'meet-in-the-middle',
    'expression parsing',
    'graph matchings',
    'ternary search',
    'matrices',
    'fft',
    'schedules',
    '2-sat',
    'string suffix structures',
    'chinese remainder theorem',
    'schedules',
    'union find',
    'combinatorial search',
    'manipulation',
]

exports.tags = tags;

